### ISSUE TITLE
dev branch for testing

### ISSUE THREAD

**Issue by TDHTTTT** [QC-UCI/qc-uci.club#49]
It seems that we don't have a dev branch for testing, right? (I saw https://github.com/QC-UCI/QC-UCI.github.io/issues/3 but not sure what that means). Is it possible on GitHub page to have a dev branch for some experiment work (possibly at another URL) before going live (since some API might not work locally)?

**Comment by omarcostahamido** [comment]
@TDHTTTT #3 is closed. That branch no longer exists since it was merged.
You are free to create a branch if you are working on something new:
- in fact you are strongly advised to do so and not experiment on the main branch!

Regarding the second question of having a live url, I'm afraid that is not possible under the same repo.
I'll advise against creating a new repo to serve as a dev repo: we'll probably loose track of the changes.
My suggestion: instead of a branch, when working on something new that you want to test at a live URL, do a fork (which is in fact what all the external contributors have done so far, since they don't have direct write permission to this repo). There you can enable a live link and share it with the rest of the team on the main issue discussion.

Let me know if that answers your question.

**Comment by TDHTTTT** [comment]
Yeah, forking definitely makes sense.
